shell.run("clear")
sleep(1)
term.setBackgroundColor(colors.white)
term.setTextColor(colors.black)
print("Anti-brick Solutions")
print("Made by Hapatapa_")
sleep(3)
shell.run("clear")
print("Applying fix... Please wait!")
shell.run("rm startup.lua")
shell.run("rm unbios.lua")
shell.run("rm startup2.lua")
shell.run("rm startup3")
shell.run("rm bios.lua")
sleep(2)
shell.run("clear")
print("Your computer has been unbricked! Please don't insert random floppies you find!")
sleep(5)
shell.run("clear")
print("Rebooting and ejecting floppy...")
sleep(1)
disk.eject("right")
disk.eject("left")
disk.eject("top")
disk.eject("bottom")
os.reboot()
